services:
  - type: web
    name: Flax
    env: node
    repo: https://github.com/Om0019/Flax.git
    branch: main
    buildCommand: npm install --include=dev
    startCommand: npm run start:stremio
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: ADDON_PUBLIC_URL
        sync: false
